services:
  postgres:
    image: postgres:16-alpine
    container_name: apexshop-postgres
    environment:
      POSTGRES_DB: apexshop
      POSTGRES_USER: apexshop
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"  # Remove if only accessed by other containers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apexshop -d apexshop"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    # Optional: Add resource limits
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./secrets/db_password.txt
