// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ApexShop.Infrastructure.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b73e2cfa-5dc6-4c3e-a36d-25e0d5c1258d"), entityTypeCount: 6)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderItem = OrderItemEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var review = ReviewEntityType.Create(this);
            var user = UserEntityType.Create(this);

            OrderEntityType.CreateForeignKey1(order, user);
            OrderItemEntityType.CreateForeignKey1(orderItem, order);
            OrderItemEntityType.CreateForeignKey2(orderItem, product);
            ProductEntityType.CreateForeignKey1(product, category);
            ReviewEntityType.CreateForeignKey1(review, product);
            ReviewEntityType.CreateForeignKey2(review, user);

            CategoryEntityType.CreateAnnotations(category);
            OrderEntityType.CreateAnnotations(order);
            OrderItemEntityType.CreateAnnotations(orderItem);
            ProductEntityType.CreateAnnotations(product);
            ReviewEntityType.CreateAnnotations(review);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
